docker-compose-yaml: docker-compose.yml

project: ciandt-drupal

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    # Enable once config sync has been setup.
    # - run:
    #     name: drush cim
    #     command: drush -y cim
    #     service: cli
    - run:
        name: If no Drupal installed run drush site-install
        command: |
          if ! drush status --fields=bootstrap | grep -q "Successful"; then
              drush -y si standard --site-name="Drupal 9 - ${LAGOON_PROJECT} ${LAGOON_GIT_BRANCH}" install_configure_form.enable_update_status_emails=NULL
          fi
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  production:
    cronjobs:
      - name: drush cron
        schedule: "M * * * *"
        command: drush cron
        service: cli
